version: '3'
services:
  sts:
    build: .
    depends_on:
      - mongo
    restart: always
    environment:
      WAIT_HOSTS: mongo:27017
      WAIT_SLEEP_INTERVAL: 2

      DOMAIN:
      DB_URL:
      GH_USER:
      GH_TOKEN:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongodb:/data/db
